hmcts/ia-home-office-mock-api

- build.gradle
> Test change

- build.gradle
RIA-3381:Update mock server to signed off API spec
Security check error resolved
##JIRA link (if applicable)##
https://tools.hmcts.net/jira/browse/RIA-3381
```
[ ] Yes
[ ] No
```
> RIA-3381:Update mock server with API spec

- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
RIA-3271:Change mock response for HO API Validation
Main applicant role added. Metadata corrected
https://tools.hmcts.net/jira/browse/RIA-3271
```
[ ] Yes
[ x] No
```
> RIA-3271:Change mock response for HO API Validation

- .travis.yml
- Dockerfile
- build.gradle
[RIA-3447](https://tools.hmcts.net/jira/browse/RIA-3447)
```
[x] Yes
[ ] No
```
> RIA-3447 upgrading to java11

- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
Modify sample response for DOB
```
[ ] Yes
[x ] No
```
> Modify sample response for DOB

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/org/openapitools/configuration/OpenAPIDocumentationConfig.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationInstructApiController.java
- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApiController.java
- src/smokeTest/java/uk/gov/hmcts/reform/iahomeofficemockapi/infrastructure/controller/SmokeTest.java
Smoke test added, Base path modified
Master branch failed for previous PR (#26) as smoke test is missing. 
New CVE suppressions had to be added
Base path modified as per home office API
```
[ ] Yes
[x ] No
```
> Smoke test added, Base path modified

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
- src/main/resources/ho-api_get-by-search-params_200-valid_response-01.json
- src/main/resources/ho-api_get-by-serach-params_200_valid-response-02.json
- src/main/resources/ho_api_get-by-search-params_200_no-data-found-cid-ref.json
- src/main/resources/ho_api_get-by-search-params_200_no-data-found-uan-ref.json
https://tools.hmcts.net/jira/browse/RIA-3564
Added additional responses for different scenarios and support for /token endpoint and to receive authorization header
```
[ ] Yes
[X] No
```
> RIA-3564: Added additional responses for different scenarios and support for /token endpoint and to receive authorization header

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
https://tools.hmcts.net/jira/browse/RIA-3564
removed redundant conditions for searchByParams
```
[ ] Yes
[X] No
```
> RIA-3564: removed redundant conditions for searchByParams

- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
- src/main/resources/ho_api_get-by-search-params_200_no-data-found-cid-ref.json
- src/main/resources/ho_api_get-by-search-params_200_no-data-found-uan-ref.json
https://tools.hmcts.net/jira/browse/RIA-3564
Changed resource loading method
```
[ ] Yes
[X] No
```
> RIA-3564: Changed resource loading method

- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
- src/main/resources/ho-api_get-by-search-params_200-valid-no-main-applicant-response-2222.json
- src/main/resources/ho-api_get-by-serach-params_200_valid-no-main-applicant-response-1111.json
- src/main/resources/ho_api_get-by-search-params_200_error-response.json
- src/main/resources/ho_api_get-by-search-params_200_invalid-format-1060.json
- src/main/resources/ho_api_get-by-search-params_200_no-appellant-found-1010.json
- src/main/resources/ho_api_get-by-search-params_200_no-ho-reference-data-found-1020.json
RIA-3545: Add mock responses for different error scenario
https://tools.hmcts.net/jira/browse/RIA-3545
```
[ ] Yes
[ x] No
```
> RIA-3545: Add mock responses for different error scenario

- config/owasp/suppressions.xml
added a suppression
```
[ ] Yes
[X] No
```
> Added a suppression

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationInstructApi.java
- src/main/resources/ho-api_instruct-response_200_valid-response-default.json
- src/main/resources/ho-api_instruct-response_500_error-response.json
https://tools.hmcts.net/jira/browse/RIA-3601
Added additional responses for instruct requests
```
[ ] Yes
[x] No
```
> RIA-3601: Added additional responses for instruct requests

- build.gradle
- charts/ia-home-office-mock-api/Chart.yaml
- charts/ia-home-office-mock-api/requirements.yaml
- config/owasp/suppressions.xml
[RIA-4056](https://tools.hmcts.net/jira/browse/RIA-4056)
```
[ ] Yes
[x] No
```
> RIA-4056 Upgrade spring-boot to 2.3.5

- build.gradle
- config/owasp/suppressions.xml
[RIA-4070](https://tools.hmcts.net/jira/browse/RIA-4070)
```
[ ] Yes
[x] No
```
> RIA-4070 Upgrade guava version 30.0

- build.gradle
- config/owasp/suppressions.xml
Remove more CVEs from this service
```
[ ] Yes
[x] No
```
> Remove more CVEs from this service

- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
- src/main/resources/ho_api_get_by_search_params_200_main_applicant_dob_match_3980.json
- src/main/resources/ho_api_get_by_search_params_200_main_applicant_name_and_dob_match_3980.json
- src/main/resources/ho_api_get_by_search_params_200_main_applicant_name_match_3980.json
[RIA-3980](https://tools.hmcts.net/jira/browse/RIA-3980)
Match the HomeOffice Applicant details against name or dob
```
[ ] Yes
[x] No
```
> RIA-3980 Match applicant by either name or dob

- src/main/resources/ho-api_get-by-serach-params_200_valid-response-default.json
[RIA-3981](https://tools.hmcts.net/jira/browse/RIA-3981)
```
[ ] Yes
[x] No
```
> RIA-3981 Home Office Validation - new error message & retry

- charts/ia-home-office-mock-api/Chart.yaml
[RIA-4278](https://tools.hmcts.net/jira/browse/RIA-4278)
upgrade Charts
```
[ ] Yes
[x] No
```
> RIA-4278 upgrade Charts

- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
- src/main/resources/ho_api_get_by_search_params_200_main_applicant_by_date.json
[RIA-3727](https://tools.hmcts.net/jira/browse/RIA-3980)
Select the applicant by max date
```
[ ] Yes
[x] No
```
> RIA-3727 Applicant by max date

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
- src/main/resources/ho-api_get-by-search-params_200-valid_response_6108.json
- src/main/resources/ho_api_get_by_search_params_200_main_applicant_dob_match_3980.json
[RIA-4557](https://tools.hmcts.net/jira/browse/RIA-4557)
Request HomeOffice data of the matching appellant details
```
[ ] Yes
[x] No
```
> RIA-4557 Request HomeOffice data of the matching appellant details

- Jenkinsfile_CNP
- build.gradle
- charts/ia-home-office-mock-api/Chart.yaml
- config/owasp/suppressions.xml
To upgrade java chart upgrade
To upgrade java chart upgrade
```
[ ] Yes
[ X] No
```
> To upgrade java chart upgrade

- charts/ia-home-office-mock-api/Chart.yaml
To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```
> To revise chart version

- .github/renovate.json
- config/owasp/suppressions.xml
> RIA-1234 replacing renovate.json with basic config

- charts/ia-home-office-mock-api/Chart.yaml
- config/owasp/suppressions.xml
> upgrading deprecated helm chart dependency

- config/owasp/suppressions.xml
> DIAC-123 suppressions update 04/12/23

- build.gradle
https://tools.hmcts.net/jira/browse/DIAC-354
```
[ ] Yes
[ ] No
```
> DIAC-354 dependency fix

- charts/ia-home-office-mock-api/Chart.yaml
- config/owasp/suppressions.xml
> DIAC-000 - dependency-suppressions

- build.gradle
> DIAC-000 Fix dependancy check

- config/owasp/suppressions.xml
> DIAC-000 - suppress dependency

- bin/init.sh
- build.gradle
https://tools.hmcts.net/jira/browse/DIAC-1418
```
[ ] Yes
[ ] No
```
> DIAC-1418 removing unnused hsytrix

- config/owasp/suppressions.xml
> DIAC-000 CVE fix
